from fpdf import FPDF
import datetime
import graphviz
import os
import tempfile

possible_paths = [
    r"C:\Program Files\Graphviz\bin",
    r"C:\Program Files (x86)\Graphviz\bin",
]
for path in possible_paths:
    if os.path.exists(path):
        os.environ["PATH"] += os.pathsep + path
        break
# --------------------------------

class ProfessionalPDF(FPDF):
    def header(self):
        self.set_fill_color(26, 37, 47) #darkblue
        self.rect(0, 0, 210, 20, 'F') #topbar
        
        self.set_y(5)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(255, 255, 255) # whitetext
        self.cell(0, 10, 'AGENTIC AI | REQUIREMENTS SPECIFICATION', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128) # Grey
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Agentic AI Core', 0, 0, 'C')

    def section_header(self, label):
        self.ln(5)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(26, 37, 47) # Dark Navy
        self.set_fill_color(230, 230, 230) # Light Grey
        # Draw a colored background box for the header
        self.cell(0, 8, f"  {label}", 0, 1, 'L', 1) 
        self.ln(2)

    def sub_header(self, label):
        self.ln(2)
        self.set_font('Arial', 'B', 11)
        self.set_text_color(41, 128, 185) # Professional Blue
        self.cell(0, 6, sanitize_text(label), 0, 1, 'L')

    def body_text(self, text):
        self.set_font('Arial', '', 10)
        self.set_text_color(50, 50, 50) # Dark Grey
        clean_text = sanitize_text(text).replace('**', '').replace('__', '')
        self.multi_cell(0, 5, clean_text)
        self.ln(1)

    def add_bullet_point(self, text):
        self.set_font('Arial', '', 10)
        self.set_text_color(50, 50, 50)
        clean_text = sanitize_text(text).replace('* ', '').replace('- ', '').replace('**', '')
        self.multi_cell(0, 5, f"  - {clean_text}")

def sanitize_text(text):
    """
    Replaces incompatible Unicode characters with ASCII equivalents
    """
    replacements = {
        '\u2022': '-', '\u2013': '-', '\u2014': '--',
        '\u2018': "'", '\u2019': "'", '\u201c': '"',
        '\u201d': '"', '\u2026': '...',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf(requirements, questions, gaps, diagram_code):
    pdf = ProfessionalPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Meta Info
    pdf.set_font('Arial', 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'R')
    pdf.ln(5)

    # --- CONTENT PROCESSOR ---
    def process_content_block(raw_text):
        lines = raw_text.split('\n')
        for line in lines:
            line = line.strip()
            if not line: continue
            if line.startswith('###') or line.startswith('##'):
                pdf.sub_header(line.replace('#', '').strip())
            elif line.startswith('* ') or line.startswith('- ') or line.startswith('•'):
                pdf.add_bullet_point(line)
            else:
                pdf.body_text(line)

    # 1. REQUIREMENTS
    pdf.section_header("1. BUSINESS & FUNCTIONAL REQUIREMENTS")
    process_content_block(requirements)
    pdf.ln(5)

    # 2. GAPS & RISKS
    pdf.add_page()
    pdf.section_header("2. IDENTIFIED GAPS & RISKS")
    process_content_block(gaps)
    pdf.ln(5)

    # 3. QUESTIONS
    pdf.add_page()
    pdf.section_header("3. CLARIFYING QUESTIONS")
    process_content_block(questions)
    
    # 4. SYSTEM ARCHITECTURE
    pdf.add_page()
    pdf.section_header("4. SYSTEM ARCHITECTURE BLUEPRINT")
    pdf.ln(5)
    
    try:
        # Generate Diagram Image
        src = graphviz.Source(diagram_code)
        src.format = 'png'
        # Render to temp file
        output_path = src.render(filename='temp_architecture', cleanup=True)
        
        # Insert Image centered
        pdf.image(output_path, x=10, w=190)
        pdf.ln(5)
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(0, 10, "Figure 1: Automated System Flow", 0, 1, 'C')
        
        if os.path.exists(output_path): os.remove(output_path)
            
    except Exception as e:
        pdf.set_font('Arial', 'I', 10)
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, "Diagram Error: Graphviz executable not found.", 0, 1)
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 5, "If you are on Windows, please restart your Terminal/VSCode after installing Graphviz.")

    return pdf.output(dest='S').encode('latin-1')